### ISSUE TITLE
Notes on emonSD-31Oct23 image creation

### ISSUE THREAD

**Issue by TrystanLea** [openenergymonitor/EmonScripts#184]
Not all services are running:

![image](https://github.com/openenergymonitor/EmonScripts/assets/503186/b03bb49c-263b-4fe9-8fbd-80ee6e2dd581)

emonhub.log does not exist

**Comment by TrystanLea** [comment]
Broken image perhaps:

> pi@emonpi:/var/log/emonhub $ python3 /opt/openenergymonitor/emonhub/src/emonhub.py --config-file=/etc/emonhub/emonhub.conf
> Traceback (most recent call last):
>   File "/opt/openenergymonitor/emonhub/src/emonhub.py", line 29, in <module>
>     from interfacers import *
>   File "/opt/openenergymonitor/emonhub/src/interfacers/EmonHubMqttInterfacer.py", line 33, in <module>
>     import paho.mqtt.client as mqtt
> ModuleNotFoundError: No module named 'paho'
> pi@emonpi:/var/log/emonhub $ sudo python3 /opt/openenergymonitor/emonhub/src/emonhub.py --config-file=/etc/emonhub/emonhub.conf
> Traceback (most recent call last):
>   File "/opt/openenergymonitor/emonhub/src/emonhub.py", line 29, in <module>
>     from interfacers import *
>   File "/opt/openenergymonitor/emonhub/src/interfacers/EmonHubMqttInterfacer.py", line 33, in <module>
>     import paho.mqtt.client as mqtt
> ModuleNotFoundError: No module named 'paho'
> pi@emonpi:/var/log/emonhub $ 
>

**Comment by TrystanLea** [comment]
Easy solution 
https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3

but perhaps should use venv
https://peps.python.org/pep-0668/

https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana
